server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${db_host:localhost}:${db_port:5432}/${db_name:nancyImmo}
    username: ${db_username:postgres}
    password: ${db_password:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
